/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookRouteImport } from './routes/webhook'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as HotelsIdRouteImport } from './routes/hotels/$id'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as ApiRolesRouteImport } from './routes/api/roles'
import { Route as ApiEmployeesRouteImport } from './routes/api/employees'
import { Route as ApiCreateEmployeeRouteImport } from './routes/api/create-employee'
import { Route as ApiClerkWebhookRouteImport } from './routes/api/clerk-webhook'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminRentalsRouteImport } from './routes/admin/rentals'
import { Route as AdminReceiptsRouteImport } from './routes/admin/receipts'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminLegalRouteImport } from './routes/admin/legal'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminHotelsRouteImport } from './routes/admin/hotels'
import { Route as AdminHallsRouteImport } from './routes/admin/halls'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminBrandingRouteImport } from './routes/admin/branding'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminArrangementsRouteImport } from './routes/admin/arrangements'

const WebhookRoute = WebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HotelsIdRoute = HotelsIdRouteImport.update({
  id: '/hotels/$id',
  path: '/hotels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRolesRoute = ApiRolesRouteImport.update({
  id: '/api/roles',
  path: '/api/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesRoute = ApiEmployeesRouteImport.update({
  id: '/api/employees',
  path: '/api/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateEmployeeRoute = ApiCreateEmployeeRouteImport.update({
  id: '/api/create-employee',
  path: '/api/create-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClerkWebhookRoute = ApiClerkWebhookRouteImport.update({
  id: '/api/clerk-webhook',
  path: '/api/clerk-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHallsRoute = AdminHallsRouteImport.update({
  id: '/halls',
  path: '/halls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArrangementsRoute = AdminArrangementsRouteImport.update({
  id: '/arrangements',
  path: '/arrangements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rentals': typeof RentalsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/webhook': typeof WebhookRoute
  '/admin/arrangements': typeof AdminArrangementsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/halls': typeof AdminHallsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/create-employee': typeof ApiCreateEmployeeRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/roles': typeof ApiRolesRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rentals': typeof RentalsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/webhook': typeof WebhookRoute
  '/admin/arrangements': typeof AdminArrangementsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/halls': typeof AdminHallsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/create-employee': typeof ApiCreateEmployeeRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/roles': typeof ApiRolesRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/admin': typeof AdminIndexRoute
  '/hotels': typeof HotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rentals': typeof RentalsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/webhook': typeof WebhookRoute
  '/admin/arrangements': typeof AdminArrangementsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/halls': typeof AdminHallsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/create-employee': typeof ApiCreateEmployeeRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/roles': typeof ApiRolesRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/faqs'
    | '/privacy'
    | '/refund'
    | '/rentals'
    | '/terms'
    | '/track'
    | '/webhook'
    | '/admin/arrangements'
    | '/admin/bookings'
    | '/admin/branding'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/faqs'
    | '/admin/halls'
    | '/admin/hotels'
    | '/admin/inventory'
    | '/admin/legal'
    | '/admin/packages'
    | '/admin/receipts'
    | '/admin/rentals'
    | '/admin/revenue'
    | '/admin/rooms'
    | '/api/callback'
    | '/api/catalog'
    | '/api/clerk-webhook'
    | '/api/create-employee'
    | '/api/employees'
    | '/api/roles'
    | '/api/send-email'
    | '/api/upload'
    | '/api/verify-payment'
    | '/hotels/$id'
    | '/admin/'
    | '/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/faqs'
    | '/privacy'
    | '/refund'
    | '/rentals'
    | '/terms'
    | '/track'
    | '/webhook'
    | '/admin/arrangements'
    | '/admin/bookings'
    | '/admin/branding'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/faqs'
    | '/admin/halls'
    | '/admin/hotels'
    | '/admin/inventory'
    | '/admin/legal'
    | '/admin/packages'
    | '/admin/receipts'
    | '/admin/rentals'
    | '/admin/revenue'
    | '/admin/rooms'
    | '/api/callback'
    | '/api/catalog'
    | '/api/clerk-webhook'
    | '/api/create-employee'
    | '/api/employees'
    | '/api/roles'
    | '/api/send-email'
    | '/api/upload'
    | '/api/verify-payment'
    | '/hotels/$id'
    | '/admin'
    | '/hotels'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/faqs'
    | '/privacy'
    | '/refund'
    | '/rentals'
    | '/terms'
    | '/track'
    | '/webhook'
    | '/admin/arrangements'
    | '/admin/bookings'
    | '/admin/branding'
    | '/admin/contacts'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/faqs'
    | '/admin/halls'
    | '/admin/hotels'
    | '/admin/inventory'
    | '/admin/legal'
    | '/admin/packages'
    | '/admin/receipts'
    | '/admin/rentals'
    | '/admin/revenue'
    | '/admin/rooms'
    | '/api/callback'
    | '/api/catalog'
    | '/api/clerk-webhook'
    | '/api/create-employee'
    | '/api/employees'
    | '/api/roles'
    | '/api/send-email'
    | '/api/upload'
    | '/api/verify-payment'
    | '/hotels/$id'
    | '/admin/'
    | '/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FaqsRoute: typeof FaqsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RentalsRoute: typeof RentalsRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  WebhookRoute: typeof WebhookRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiClerkWebhookRoute: typeof ApiClerkWebhookRoute
  ApiCreateEmployeeRoute: typeof ApiCreateEmployeeRoute
  ApiEmployeesRoute: typeof ApiEmployeesRoute
  ApiRolesRoute: typeof ApiRolesRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  HotelsIdRoute: typeof HotelsIdRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook': {
      id: '/webhook'
      path: '/webhook'
      fullPath: '/webhook'
      preLoaderRoute: typeof WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hotels/$id': {
      id: '/hotels/$id'
      path: '/hotels/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof HotelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roles': {
      id: '/api/roles'
      path: '/api/roles'
      fullPath: '/api/roles'
      preLoaderRoute: typeof ApiRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees': {
      id: '/api/employees'
      path: '/api/employees'
      fullPath: '/api/employees'
      preLoaderRoute: typeof ApiEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-employee': {
      id: '/api/create-employee'
      path: '/api/create-employee'
      fullPath: '/api/create-employee'
      preLoaderRoute: typeof ApiCreateEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clerk-webhook': {
      id: '/api/clerk-webhook'
      path: '/api/clerk-webhook'
      fullPath: '/api/clerk-webhook'
      preLoaderRoute: typeof ApiClerkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/halls': {
      id: '/admin/halls'
      path: '/halls'
      fullPath: '/admin/halls'
      preLoaderRoute: typeof AdminHallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arrangements': {
      id: '/admin/arrangements'
      path: '/arrangements'
      fullPath: '/admin/arrangements'
      preLoaderRoute: typeof AdminArrangementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArrangementsRoute: typeof AdminArrangementsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminHallsRoute: typeof AdminHallsRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminRentalsRoute: typeof AdminRentalsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArrangementsRoute: AdminArrangementsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminHallsRoute: AdminHallsRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminRentalsRoute: AdminRentalsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FaqsRoute: FaqsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RentalsRoute: RentalsRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  WebhookRoute: WebhookRoute,
  ApiCallbackRoute: ApiCallbackRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiClerkWebhookRoute: ApiClerkWebhookRoute,
  ApiCreateEmployeeRoute: ApiCreateEmployeeRoute,
  ApiEmployeesRoute: ApiEmployeesRoute,
  ApiRolesRoute: ApiRolesRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  HotelsIdRoute: HotelsIdRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
